import Ruler from "@/script/ruler";


const Plants = {
    "ANDROSEME OFFICINALE HYPERICUM ANDROSOEMUM": Ruler.Saturn,
    "BLEUET DES CHAMPS CENTAUREA CYANUS": Ruler.Saturn,
    "BOURSE A PASTEUR CAPSELLA BURSA PASTORIS": Ruler.Saturn,
    "BUPLEVRE A FEUILLES RONDES BUPLEURUM ROTUNDIFOLIUS": Ruler.Saturn,
    "CAPILLAIRE ROUGE ASPLENIUM TRICHOMANES": Ruler.Saturn,
    "CUSCUTES CUSCUTA": Ruler.Saturn,
    "EGOPODE AEGOPODIUM PODOGARIA": Ruler.Saturn,
    "EPILOBES EPILOBIUM": Ruler.Saturn,
    "FUMETERRE OFFICINALE FUMARIA OFFICINALIS": Ruler.Saturn,
    "GRANDE CONSOUDE SYMPHYTUM OFFICINALIS": Ruler.Saturn,
    "HERBE AUX PUCES PLANTAGO PSYLLIUM": Ruler.Saturn,
    "HETRE FAGUS SILVATICA": Ruler.Saturn,
    "IF TAXUS BACCATA": Ruler.Saturn,
    "JACEE CENTAUREA JACEA": Ruler.Saturn,
    "LOTIER CORNICULE LOTUS CORNICULATUS": Ruler.Saturn,
    "NEFLIER MESPILUS GERMANICA": Ruler.Saturn,
    "ORGE HORDEUM SATIVUM": Ruler.Saturn,
    "ORME ULMUS": Ruler.Saturn,
    "OSMONDE OSMONDA REGALIS": Ruler.Saturn,
    "PENSEE VIOLA TRICOLOR": Ruler.Saturn,
    "PETIT BOUILLON BLANC (MOLENE) VERBASCUM THAPSES": Ruler.Saturn,
    "PEUPLIER POPULUS": Ruler.Saturn,
    "POLYPODE POLYPODIUM VULGARE": Ruler.Saturn,
    "PRELE DES CHAMPS EQUISETUM ARVENSE": Ruler.Saturn,
    "PYROLE A GRAPPES PIRULA ROTUNDIFOLIA": Ruler.Saturn,
    "RENOUEE DES OISEAUX POLYGONUM AVICULAIRE": Ruler.Saturn,
    "SCEAU DE SALOMON POLYGONATUM": Ruler.Saturn,
    "TAMARIS TAMARIX": Ruler.Saturn,

    "AIGREMOINE COMMUNE AGRIMONIA":Ruler.Jupiter,
    "AIRELLE MYRTILLE VACCINIUM MYRTILLUS":Ruler.Jupiter,
    "ASPERGE ASPARAGUS":Ruler.Jupiter,
    "BASLAMITE CHRYSANTHEMUM BALSAMITA":Ruler.Jupiter,
    "BOURRACHE OFFICINALE BORAGO OFFICINALIS":Ruler.Jupiter,
    "CERFEUIL ANTHRISCUS":Ruler.Jupiter,
    "CHARDON MARIE SIBYLUM MARIANUM":Ruler.Jupiter,
    "CHATAIGNIER CASTANEA SATIVA":Ruler.Jupiter,
    "CHENE QUERCUS":Ruler.Jupiter,
    "CHIENDENT CYNODON DACTYLON":Ruler.Jupiter,
    "COCHLEARIA COCHLEARIA":Ruler.Jupiter,
    "ENDIVE CICHORIUM ENDIVA":Ruler.Jupiter,
    "FIGUIER FIGUS CARICA":Ruler.Jupiter,
    "HEPATIQUE ANEMONE HEPATICA":Ruler.Jupiter,
    "HYSOPE HYSOPUS OFFICINALIS":Ruler.Jupiter,
    "JOUBARBE SEMPERVIVUM":Ruler.Jupiter,
    "MACERON SMYRNIUM OLUSATRUM":Ruler.Jupiter,
    "MELITOT OFFICINALE MELILOTUS OFFICINALIS":Ruler.Jupiter,
    "MELISSE OFFICINALE MILISSA OFFICINALIS":Ruler.Jupiter,
    "PATIENCE RUMEX":Ruler.Jupiter,
    "PISSENLIT DENT DE LION TARAXACUM OFFICINALIS":Ruler.Jupiter,
    "PULMONAIRE PULMONARIA":Ruler.Jupiter,
    "QUINTEFEUILLE POTENTILLA REPTANS":Ruler.Jupiter,
    "ROSIER ROSA":Ruler.Jupiter,
    "SAUGE SALVIA":Ruler.Jupiter,
    "SCOLOPENDRE SCOLOPENDRIUM":Ruler.Jupiter,

    "ABSINTHE ARTEMISIA ABSINTHIUM" : Ruler.Mars,
    "AIL COMMUN ALLIUM SATIVUM" : Ruler.Mars,
    "AUBEPINE CRATAEGUS (with saturn)" : Ruler.Mars,
    "BASILIC OCYMUM BASILICUM" : Ruler.Mars,
    "BOUTON D'OR BULBEUX RANONCULUS BULBOSUS" : Ruler.Mars,
    "BRYONE DIOIQUE BRYONIA DIOICA" : Ruler.Mars,
    "CHAUSSE-TRAPPE CENTAUREA CALCITRAPA" : Ruler.Mars,
    "EPINE VINETTE COMMUNE BERBERIS VULGARIS" : Ruler.Mars,
    "GARANCE TINCTORIALE RUBIA TINCTORUM" : Ruler.Mars,
    "GENTIANE GENTIANA" : Ruler.Mars,
    "GRANDE ORTIE URTICA DIOICA" : Ruler.Mars,
    "GRAND RAIFORT ARMORACIA IMPATHIFOLIA" : Ruler.Mars,
    "GRATIOLE OFFICINALE GRATOLIA OFFICINALIS" : Ruler.Mars,
    "HOUBLON HUMULUS LUPULUS" : Ruler.Mars,
    "IMPERATOIRE PEULEDANUM OSTRUTHIUM" : Ruler.Mars,
    "IVETTE COMMUNE AJUGA CHAMEAOPITYS" : Ruler.Mars,
    "LOBELIE BRULANTE LOBELIA URENS" : Ruler.Mars,
    "OIGNON ALLIUM CEPA" : Ruler.Mars,
    "PASSERAGE LEPIDIUM" : Ruler.Mars,
    "RHUBARBE RHEUM" : Ruler.Mars,
    "SABINE JUNIPERUS SABINA" : Ruler.Mars,
    "TABAC" : Ruler.Mars,

    "ALCHEMILLE COMMUNE ALCHIMILLA VULGARIS": Ruler.Venus,
    "ARTICHAUT CYRANA SCOLYMUS": Ruler.Venus,
    "BARDANE ARCTIUM": Ruler.Venus,
    "BAUDREMOINE MEUM ATHAMANTICUM": Ruler.Venus,
    "BOGLOSSE OFFICINALE ANCHUSA OFFICINALIS": Ruler.Venus,
    "BRUNELLE VULGAIRE BRUNELLA VULGARIS": Ruler.Venus,
    "CATAIRE NEPETA CATARIA": Ruler.Venus,
    "CROISETTE GALIUM CRUCIATA": Ruler.Venus,
    "EPINARD SPINACIA OLERACEA": Ruler.Venus,
    "FILIPENDULE COMMUNE FILIPENDULA HEXAPETALA": Ruler.Venus,
    "FRAISIER SAUVAGE FRAGARIA VESCA": Ruler.Venus,
    "GRANDE OSEILLE RUMEX ACETOSA": Ruler.Venus,
    "GROSEILLER A MAQUEREAUX RIBES UVA CRISPA": Ruler.Venus,
    "GUIMAUVE OFFICINALE ALTHAEA OFFICINALIS": Ruler.Venus,
    "MARGUERITE DES PRES CHRYSANTHENUM LEUCANTHENUM": Ruler.Venus,
    "MENTHE MENTHA": Ruler.Venus,
    "MERCURIALE ANNUELLE MERCURIALIS ANNUA": Ruler.Venus,
    "MILLEFEUILLE ACHILLEA MELLEFOLIUM": Ruler.Venus,
    "PETITE PERVENCHE VINCA MINOR": Ruler.Venus,
    "POIRIER PYRUS COMMUNIS": Ruler.Venus,
    "POIS CHICHE CICER ARIETINUM": Ruler.Venus,
    "PRIMEVERE OFFICINALE PRIMULA OFFICINALIS": Ruler.Venus,
    "REINE DES PRES FILIPENDULA ULMARIA": Ruler.Venus,
    "RONCE DES BUISSONS RUBUS FRUTICOSUS": Ruler.Venus,
    "SANICLE SANICULA": Ruler.Venus,
    "SUCCISE SUCCISA PRAEMORSA": Ruler.Venus,
    "TROENE LIGUSTRUM": Ruler.Venus,
    "TUSSILAGE PAS D'ANE TUSSILAGO FARFARA": Ruler.Venus,
    "VERVEINE OFFICINALE VERBENA OFFICINALIS": Ruler.Venus,


    "celery APIUM GRAVEOLENS" : Ruler.Mercury,
    "ALLIAIRE OFFICINALE ALLIARA OFFICINALIS" : Ruler.Mercury,
    "ANETH ODORANT ANETHUM GRAVEOLENS" : Ruler.Mercury,
    "AURONE ARTEMISIA ABROMATUM" : Ruler.Mercury,
    "AVOINE AVENA SATIVA" : Ruler.Mercury,
    "CALAMENT OFFICINAL CALAMINTHA OFFICINALIS" : Ruler.Mercury,
    "CAPILLAIRE BLANC ASPLENIUM RUTA MURARIA" : Ruler.Mercury,
    "CAROTTE SAUVAGE DAUCUS CAROTA" : Ruler.Mercury,
    "CARVI OFFICINAL CARUM CARVI" : Ruler.Mercury,
    "CHEVREFEUILLE DES BOIS LONICERA PERICLYMENUM" : Ruler.Mercury,
    "DOUCE AMERE SOLANUM DULCAMARA" : Ruler.Mercury,
    "FENOUIL FOENICULUM VULGARE" : Ruler.Mercury,
    "GRANDE AUNEE INULA HELENIUM" : Ruler.Mercury,
    "LAVANDE OFFICINALE LAVANDULA OFFICINALIS" : Ruler.Mercury,
    "MARJOLAINE MAJORANA HORTENSIS" : Ruler.Mercury,
    "MARRUBE VULGAIRE MARRUBIUM VULGARE" : Ruler.Mercury,
    "MUGUET CONVALLARIA MAIALIS" : Ruler.Mercury,
    "MURIER MORUS" : Ruler.Mercury,
    "NOISETIER COUDRIER CORYLUS AVELLANA" : Ruler.Mercury,
    "PARIETAIRE OFFICINALE PARIETARIA OFFICINALIS" : Ruler.Mercury,
    "REGLISSE GLABRE GLYCYRRAHIZA GLABRA" : Ruler.Mercury,
    "SARRIETTE DES JARDINS SATUREIA HORTENSIS" : Ruler.Mercury,
    "SAXIFRAGE A TROIS DOIGTS SAXIFRAGA TRIDACTYLES" : Ruler.Mercury,

    "ANGELIQUE ARCHANGELIQUE ANGELICA ARCHANGELICA" : Ruler.Sun,
    "CAMOMILLE ROMAINE ANTHEMIS NOBILIS" : Ruler.Sun,
    "CHELIDOINE CHELIDONIUM MAJUS" : Ruler.Sun,
    "CRITHME MARINE CRITHMUM MARITIMUM" : Ruler.Sun,
    "EUPHRAISE (CASSE LUNETTES) EUPHRASIA" : Ruler.Sun,
    "FRENE COMMUN FRAXINUS EXCELSIOR" : Ruler.Sun,
    "GENEVRIER JUNIPERUS COMMUNIS" : Ruler.Sun,
    "HELIOTROPE HELIOTROPIUM EUROPAENUM" : Ruler.Sun,
    "LAURIER LAURUS NOBILIS" : Ruler.Sun,
    "LIVECHE LEVISTICUM OFFICINALIS" : Ruler.Sun,
    "MILLEPERTUIS HYPERICUM PERFORATUM" : Ruler.Sun,
    "NOYER JUGLANS" : Ruler.Sun,
    "PETITE CENTAUREE COMMUNE CENTAURIUM VULGARE" : Ruler.Sun,
    "PIMPRENELLE SANGUISORBA" : Ruler.Sun,
    "ROMARIN ROSMARINUS OFFICINALIS" : Ruler.Sun,
    "RUE FETIDE RUTA GRAVEOLENS" : Ruler.Sun,
    "SAFRAN D'AUTOMNE CROCUS SATIVUS" : Ruler.Sun,
    "SOUCI COMMUN CALENDULA OFFICINALIS" : Ruler.Sun,
    "TORMENTILLE POTENTILLA" : Ruler.Sun,
    "TREFLE DES PRES TRIFOLIA" : Ruler.Sun,
    "VIPERINE ECHIUM" : Ruler.Sun,


    "ACANTHE MOLLE ACANTHUS MOLLIS" : Ruler.Moon,
    "CARDAMINE" : Ruler.Moon,
    "CHATAIGNE D'EAU TRAPA NATANS" : Ruler.Moon,
    "CHOU BRASSICA" : Ruler.Moon,
    "CONCOMBRE CUCUMIS SATIVUS" : Ruler.Moon,
    "CRESSON DE FONTAINE NASTURTIUM OFFICINALIS" : Ruler.Moon,
    "DENTAIRE DENTARIA" : Ruler.Moon,
    "GRANDE SALICAIRE LUTHRUM SALICARIA" : Ruler.Moon,
    "GRATTERON GALIUM APARINE" : Ruler.Moon,
    "IRIS" : Ruler.Moon,
    "LAITUE CULTIVEE LACTUCA SATIVA" : Ruler.Moon,
    "LIS BLANC LILIUM CANDICUM" : Ruler.Moon,
    "MORGELINE STELLARIA MEDIA" : Ruler.Moon,
    "PILOSELLE HIERACIUM PILOSELLA" : Ruler.Moon,
    "PYRETHRE ANACYCLUS" : Ruler.Moon,
    "SAULE SALIX" : Ruler.Moon,
    "SAXIFRAGE SAXIFRAGA" : Ruler.Moon,
    "SCLAREE SALVIA SCLAREA" : Ruler.Moon,
    "VERONIQUE VERONICA" : Ruler.Moon,

    "Althaea officinalis : marshmallow (with Jupiter and Venus)": Ruler.Sun,
    "Anagallis arvensis : common scarlet pimpernel (with Jupiter)": Ruler.Sun,
    "Angelica silvestris : wild angelica (with Venus)": Ruler.Sun,
    "Calamus aromaticus (Acorus calamus): calamus": Ruler.Sun,
    "Caryophyllus (Syzygium aromaticum) : clove tree": Ruler.Sun,
    "Cinnamonum ceylanicum : cinnamon, Ceylon cinnamon": Ruler.Sun,
    "Citrus aurantium : orange tree": Ruler.Sun,
    "Citrus bergamium : bergamot": Ruler.Sun,
    "Citrus limonum : lemon tree": Ruler.Sun,
    "Dictamnus albus: dittany": Ruler.Sun,
    "Drosera rotundifolia : sundew": Ruler.Sun,
    "Echium valgare : viper's buglass, blueweed": Ruler.Sun,
    "Erythrea centaurium (Entaurium umbellatum) : lesser centaury": Ruler.Sun,
    "Fragaria vesca : wild strawberry (with Jupiter)": Ruler.Sun,
    "Fraxinus excelsior: ash (with Jupiter)": Ruler.Sun,
    "Gentian lutea : gentian (with Jupiter)": Ruler.Sun,
    "Glechoma hederacea : ground ivy (with Venus)": Ruler.Sun,
    "Helianthus anuus : sunflower": Ruler.Sun,
    "Inula helenium : elecampane": Ruler.Sun,
    "Matricaria chamomilla : German chamomile": Ruler.Sun,
    "Melissa officinalis : lemon balm (with Jupiter)": Ruler.Sun,
    "lea europea : olive tree (with Jupiter)": Ruler.Sun,
    "Oryza sativa: rice": Ruler.Sun,
    "Paeonia offcinalis: peony": Ruler.Sun,
    "Passiflora incarnata : passionflower": Ruler.Sun,
    "Piper: pepper (white and black)": Ruler.Sun,
    "Plantago lanceolata : ribwort (with Mars)": Ruler.Sun,
    "Plantago major : plantain (with Mars)": Ruler.Sun,
    "Ruta graveolens: common rue": Ruler.Sun,
    "Sinapis alba : white mustard": Ruler.Sun,
    "Sinapis nigra : black mustard": Ruler.Sun,
    "Viscum album : mistletoe (with juniper and moon)": Ruler.Sun,
    "Vitis vinifera: grapevine (with Jupiter and moon)": Ruler.Sun,
    "Zedoaria (Curcuma zedoaria) : zedoary": Ruler.Sun,
    "Zingiber officinale : ginger": Ruler.Sun,

    "Agnus castus : monk's pepper":Ruler.Moon,
    "Atriplex silvestris : atriplex, orache, all-seed, notchweed":Ruler.Moon,
    "Bellis perennis : daisy":Ruler.Moon,
    "Carica papaya : papaya":Ruler.Moon,
    "Cheiranthus cheiri: wallflower":Ruler.Moon,
    "Cucurbita Pepo: pumpkin, gourd":Ruler.Moon,
    "Curcuma longa : turmeric":Ruler.Moon,
    "Calium aparine : galium, cleavers, goose grass":Ruler.Moon,
    "Hyssopus officinalis : hyssop":Ruler.Moon,
    "Lenticula palustris : duckweed":Ruler.Moon,
    "Ligustrum vulgare : privet":Ruler.Moon,
    "Lilium album : white lily":Ruler.Moon,
    "Lysimachia nummularia: moneywort":Ruler.Moon,
    "Myristica fragrans: nutmeg":Ruler.Moon,
    "Nymphaea alba : water lily":Ruler.Moon,
    "Papaver rhoeas: corn poppy (with Saturn)":Ruler.Moon,
    "Papaver somniferum: opium poppy (with Saturn)":Ruler.Moon,
    "Ruta lunaria: moonwort":Ruler.Moon,
    "Sedum acre: sharp stonecrop, wall-pepper":Ruler.Moon,
    "Sedum telephium: orpine":Ruler.Moon,
    "Telephium vulgare: sedum":Ruler.Moon,
    "Tilia: lime-tree (with Venus)":Ruler.Moon,
    "Vinca minor: myrtle, periwinkle":Ruler.Moon,

    "Adiantum capillus veneris : maidenhair": Ruler.Mercury,
    "Acacia : all kinds of acacias": Ruler.Mercury,
    "Alliaria officinalis: garlic, hedge-mustard": Ruler.Mercury,
    "Artemisia abrotanum: southernwood": Ruler.Mercury,
    "Artemisia absinthium : wormwood (with Venus)": Ruler.Mercury,
    "Avena saliva: oats (with Jupiter)": Ruler.Mercury,
    "Azalea : azalea": Ruler.Mercury,
    "Bryonia albs: bryony": Ruler.Mercury,
    "Calamintha montana : calamint, mountain balm, wild basil": Ruler.Mercury,
    "Calamintha arvensis : mint, calamint": Ruler.Mercury,
    "Chichorium endivia: endive, chicory": Ruler.Mercury,
    "Cynoglossum officinale : hound's tongue (with Jupiter)": Ruler.Mercury,
    "Digitalis purpurea: digitalis, red foxglove": Ruler.Mercury,
    "Glycyrrhiza glabra: licorice": Ruler.Mercury,
    "Inula helenium: elecampane": Ruler.Mercury,
    "Lonicera caprifolium : honeysuckle, woodbine": Ruler.Mercury,
    "Mandragora: mandrake (with Saturn and the Moon)": Ruler.Mercury,
    "Mercurialis annua: mercury, annual": Ruler.Mercury,
    "Mercurialis perennis: perennial mercury": Ruler.Mercury,
    "Myrtus communis: myrtle": Ruler.Mercury,
    "Origanum vulgare: oregano, origanum": Ruler.Mercury,
    "Parietaria officinalis : wall pellitory": Ruler.Mercury,
    "Pastinaca sativa : parsnip": Ruler.Mercury,
    "Petroselinum hortense: parsley": Ruler.Mercury,
    "Pimpinella anisum: anise": Ruler.Mercury,
    "Piper cubeba : cubeb pepper": Ruler.Mercury,
    "Satureja hortensis : savory": Ruler.Mercury,
    "Solanum dulcamara : bittersweet": Ruler.Mercury,
    "Strychnos nux vomica: vomic or poison nut": Ruler.Mercury,
    "Teucrium scordium: germander": Ruler.Mercury,
    "Trifolium arvense: barefoot, hop trefoil, hopclover": Ruler.Mercury,
    "Trifolium fibrinum: marsh trefoil, buckbean": Ruler.Mercury,
    "Tussilago farfara: coltsfoot": Ruler.Mercury,
    "Valerian ofcinalis : valerian": Ruler.Mercury,


    "Allium cepa : common onion": Ruler.Mars,
    "Aloe : all kinds of aloe (with Saturn)": Ruler.Mars,
    "Ananas sativus: pineapple": Ruler.Mars,
    "Anemone: anemone": Ruler.Mars,
    "Artemisia absinthium : wormwood with Venus and Mercury": Ruler.Mars,
    "Arum maculatum : cuckoopint, wake-robin": Ruler.Mars,
    "Bellis perennis : daisy (with the Moon)": Ruler.Mars,
    "Buxus sempervirens : box": Ruler.Mars,
    "Cassia obovata : senna": Ruler.Mars,
    "Capsicum : paprika, red pepper, various kinds": Ruler.Mars,
    "Carduus benedictus : avens, blessed thistle": Ruler.Mars,
    "Cochlearia armoracia: horseradish": Ruler.Mars,
    "Coriandrum sativum: coriander (with Venus)": Ruler.Mars,
    "Genista tinctoria: dyer's broom": Ruler.Mars,
    "Geranium robertianum: geranium, herb Robert (with Venus)": Ruler.Mars,
    "Gratiola officinalis : hedge hyssop": Ruler.Mars,
    "Helichrysum arenarium: everlasting flower, immortelle, goldflower": Ruler.Mars,
    "Lamium album: dead nettle, blind nettle, lamium": Ruler.Mars,
    "Linum usatissimum : flax (with Jupiter and Saturn)": Ruler.Mars,
    "Lonicera caprifolium : honeysuckle, woodbine (with Mercury)": Ruler.Mars,
    "Mezereum : spurge-laurel, mezereon": Ruler.Mars,
    "Nepeta cataria catnip": Ruler.Mars,
    "Ononis spinosa : restharrow, thorny harrow": Ruler.Mars,
    "Pinus : pine, all kinds": Ruler.Mars,
    "Plantago major: plantain (with the Sun)": Ruler.Mars,
    "Quercus robur: oak (with Jupiter)": Ruler.Mars,
    "Ranunculus sceleratus : cursed crowfoot, marsh crowfoot (with Venus)": Ruler.Mars,
    "Raphanus sativus : black radish": Ruler.Mars,
    "Rosa canina : dogrose (with Jupiter)": Ruler.Mars,
    "Rubia tinctorum : madder (with Jupiter)": Ruler.Mars,
    "Sambucus ebulus: dwarf elder": Ruler.Mars,
    "Scilla maritima sea onion, squill (with Saturn)": Ruler.Mars,
    "Scrophularia nodosa : common figwort, knotty brownwort": Ruler.Mars,
    "Smilax utilis sarsaparilla": Ruler.Mars,
    "Sinapis : all kinds of mustard": Ruler.Mars,
    "Strychnus nux vomica : poison nut, emetic nut": Ruler.Mars,
    "Tormentilla : tormentil, bloodwort, rootwort (with the Sun)": Ruler.Mars,
    "Urtica urens : small stinging nettle (with Pluto)": Ruler.Mars,



    "Acer : maple, sycamore" : Ruler.Jupiter,
    "Aesculus hippocastanum: horse chestnut" : Ruler.Jupiter,
    "Agropyron cannium: couch grass, dog grass" : Ruler.Jupiter,
    "Althaea officinalis : marshmallow (with the Sun and Venus" : Ruler.Jupiter,
    "Amygdalum: almond (with the Sun)" : Ruler.Jupiter,
    "Anagallis arvensis : scarlet pimpernel" : Ruler.Jupiter,
    "Arnica montana : arnica" : Ruler.Jupiter,
    "Avena sativa : oats (with Mercury)" : Ruler.Jupiter,
    "Betonica officinalis : hedge-nettle, stachys, woundwort" : Ruler.Jupiter,
    "Borrago officinalis : borage" : Ruler.Jupiter,
    "Centaurium umbellatum : centaury" : Ruler.Jupiter,
    "Cetraria islandica: Carrageen or Irish moss" : Ruler.Jupiter,
    "Chelidonium majus: celandine (with the Sun)" : Ruler.Jupiter,
    "Cichoriurn intybus : chicory" : Ruler.Jupiter,
    "Dianthus cariophyllus : carnation" : Ruler.Jupiter,
    "Ficus carica : fig (with Vpnus)" : Ruler.Jupiter,
    "Foeniculum vulgare : fennel (with Mercury)" : Ruler.Jupiter,
    "Fraxinus excelsior: ash (with the Sun)" : Ruler.Jupiter,
    "Fraxinus ornus: manna, flowering ash" : Ruler.Jupiter,
    "Fumaria officinalis : fumitory" : Ruler.Jupiter,
    "Gentiana lutea : gentian, yellow (with the Sun)" : Ruler.Jupiter,
    "Hepaticae: liverwort, different kinds" : Ruler.Jupiter,
    "Hyoscyamus niger: henbane (with Saturn and Neptune)" : Ruler.Jupiter,
    "Hyssopus officinalis : hyssop (with the Moon and Mars)" : Ruler.Jupiter,
    "Imperatoria : masterwort " : Ruler.Jupiter,
    "Inula campana: elecampane" : Ruler.Jupiter,
    "Jasminum: jasmine" : Ruler.Jupiter,
    "Juniperus communis : juniper (with the Sun and Mercury)" : Ruler.Jupiter,
    "Laurus nobilis : laurel (with the Sun), bay" : Ruler.Jupiter,
    "Lavandula vera : lavender (with the Sun and Mercury)" : Ruler.Jupiter,
    "Linum usitatissimum : flax (with Saturn and Mars)" : Ruler.Jupiter,
    "Liquiritia officinalis (Glycyrrhiza glabra) : licorice (with Mercury)" : Ruler.Jupiter,
    "Marchantia polymorpha : a kind of Irish moss, liverwort" : Ruler.Jupiter,
    "Mentha piperita : peppermint (with Venus)" : Ruler.Jupiter,
    "Myristica fragrans: nutmeg (with the Moon) or nutmeg tree" : Ruler.Jupiter,
    "Myrrha: myrrh (with the Sun)" : Ruler.Jupiter,
    "Ocimum basilicum: basil (with Mars)" : Ruler.Jupiter,
    "Olea europaea: olive (with the Sun) or olive tree" : Ruler.Jupiter,
    "Panax ginseng: ginseng" : Ruler.Jupiter,
    "Pimpinella anisum : anise (with Mercury)" : Ruler.Jupiter,
    "Pirus malus : apple tree" : Ruler.Jupiter,
    "Polypodium vulgare: polypody" : Ruler.Jupiter,
    "Populus: all kinds of poplars (with Saturn and the Sun)" : Ruler.Jupiter,
    "Prunus armeniaca : apricot tree" : Ruler.Jupiter,
    "Rosa canina: dogrose (with Mars)" : Ruler.Jupiter,
    "Rosa damascena : rose (with Venus)" : Ruler.Jupiter,
    "Rubia tinctorum : madder" : Ruler.Jupiter,
    "Rubus idaeus : raspberry" : Ruler.Jupiter,
    "Saccharum officinalis : sugarcane" : Ruler.Jupiter,
    "Santalum album : white sandalwood (with Venus)" : Ruler.Jupiter,
    "Santalum rubrum : red sandalwood (with Venus)" : Ruler.Jupiter,
    "Sempervivurn tectorum : sempervivum, houseleek" : Ruler.Jupiter,
    "Solanurn lycopersicurn : tomato" : Ruler.Jupiter,
    "Symphytum officinale : comfrey" : Ruler.Jupiter,
    "Tanacetum vulgare: tansy" : Ruler.Jupiter,
    "Tilia europaea : lime tree (with Venus)" : Ruler.Jupiter,
    "Tussilago farfara : coltsfoot (with Mercury)" : Ruler.Jupiter,
    "Verbascum thapsiforme: mullein" : Ruler.Jupiter,
    "Viscum album : mistletoe (with the Sun and Moon)" : Ruler.Jupiter,
    "Vitis vinifera: grapewine (with the Sun)" : Ruler.Jupiter,

    "Aconitum napellus : aconite, monkshood (with Mars)": Ruler.Saturn,
    "bishop's weed, or herb gerard": Ruler.Saturn,
    "Aloe : aloe (with Mars)": Ruler.Saturn,
    "Allium cepa: kitchen onion (with Mars and the Moon)": Ruler.Saturn,
    "Amaranthus : amaranth": Ruler.Saturn,
    "Arctium lappa : bur, burdock (with Venus)": Ruler.Saturn,
    "Asplenium: spleenwort": Ruler.Saturn,
    "Atropa belladonna: belladonna, deadly nightshade (with Mars)": Ruler.Saturn,
    "Auricularia judae : jew's ear": Ruler.Saturn,
    "Beta vulgaris : beetroot": Ruler.Saturn,
    "Beta rubra : beet, mangel-wurzel, stock beet, silver beet": Ruler.Saturn,
    "Cannabis saliva: hemp (with Neptune)": Ruler.Saturn,
    "Carvurn carvi: caraway (with Mercury)": Ruler.Saturn,
    "Carvurn cari: caraway (with Mercury)": Ruler.Saturn,
    "Cicuta virosa: cowbane, water hemlock": Ruler.Saturn,
    "Conium maculatum : hemlock (with Neptune and Uranus)": Ruler.Saturn,
    "Cydonia vulgaris : quince": Ruler.Saturn,
    "Digitalis pupurea : digitalis, foxglove (with Mercury and Venus)": Ruler.Saturn,
    "Eryngium maritimum : eryngium, sea holly": Ruler.Saturn,
    "Eryngium campestre: eryngo (common)": Ruler.Saturn,
    "Eryngium planum : flatleaved eryngo": Ruler.Saturn,
    "Filix mas (Aspidium filix mas): male fern": Ruler.Saturn,
    "Foenum graecum: fenugreek": Ruler.Saturn,
    "Gaultheria procumbens : wintergreen": Ruler.Saturn,
    "Hedera helix: ivy": Ruler.Saturn,
    "Helleborus niger. hellebore, Christmas rose": Ruler.Saturn,
    "Hieracium pilosella : hawkweed": Ruler.Saturn,
    "Hyoscyamus niger: henbane (with Jupiter and Neptune)": Ruler.Saturn,
    "Ilex aquifolium: holly": Ruler.Saturn,
    "Iris florentina: Florentine iris (with the Moon)": Ruler.Saturn,
    "Iris germanica : German iris (with t* Moon), dark blue flowers": Ruler.Saturn,
    "Iris pallida: pale iris (with the Moon), dark blue flowers": Ruler.Saturn,
    "Linum usitatissimum : flax (with Jupiter and Mars)": Ruler.Saturn,
    "Listera ovata: twayblade": Ruler.Saturn,
    "Lolium temulentum : bearded darnel, cockle weed": Ruler.Saturn,
    "Mandragora officinarum : mandrake (with Mercury and the Moon)": Ruler.Saturn,
    "Osmunda regalis : royal fern (with the Moon)": Ruler.Saturn,
    "Papaver rhoeas: corn poppy (with the Moon)": Ruler.Saturn,
    "Papaver somniferum: opium poppy (with the Moon)": Ruler.Saturn,
    "Pinus sylvestris: Scotch pine": Ruler.Saturn,
    "Plantago coronopus: plantain": Ruler.Saturn,
    "Polygonum vulgare: polypody root": Ruler.Saturn,
    "Prunus spinosa: sloe, white plum, blackthorn": Ruler.Saturn,
    "Rhamnus frangula: alder buckthorn": Ruler.Saturn,
    "Sambucus nigra : black elder (with Mercury and Venus)": Ruler.Saturn,
    "Scilla maritima : squill, sea onion, (with Mars)": Ruler.Saturn,
    "Secale cereale : rye": Ruler.Saturn,
    "Senna : senna": Ruler.Saturn,
    "Solanum dulcamara : bittersweet nightshade": Ruler.Saturn,
    "Sorbus domestica : service or sorb tree": Ruler.Saturn,
    "Stellaria media: chickweed": Ruler.Saturn,
    "Tamarindus indica : tamarind": Ruler.Saturn,
    "Veratrum album : white hellebore": Ruler.Saturn,
    "Vinca minor: periwinkle (with the Moon)": Ruler.Saturn,
    "Zea mays : maize, Indian corn": Ruler.Saturn,

    "Ajuga reptans : bugle": Ruler.Venus,
    "Akhemilla vulgaris : lady's mantle": Ruler.Venus,
    "Alkanna tinctoria : dyer's alkanet": Ruler.Venus,
    "Aquilegia vulgaris : columbine": Ruler.Venus,
    "Artemisia absinthium": Ruler.Venus,
    "wormwood (with Mercury and Mars)": Ruler.Venus,
    "Artemisia vulgaris : mugwort": Ruler.Venus,
    "Betula pendula (= verrucosa) : a kind of birch": Ruler.Venus,
    "Betula pubescens (= alba) : a kind of birch": Ruler.Venus,
    "Castanea sativa : chestnut (with Jupiter)": Ruler.Venus,
    "Cotyledon umbilicus : navelwort, cotyledon": Ruler.Venus,
    "Cynara scolymus: artichoke": Ruler.Venus,
    "Digitalis purpurea : digitalis, red foxglove (with Mercury and": Ruler.Venus,
    "Saturn)": Ruler.Venus,
    "Dipsacus sativus : teasel, fuller's thistle or weed": Ruler.Venus,
    "Geranium robertianum: geranium, herb Robert (with Mars)": Ruler.Venus,
    "Glechoma hedera: ground ivy (with the Sun)": Ruler.Venus,
    "Leonurus cardiaca : motherwort": Ruler.Venus,
    "Lithospermum minus : gromwell": Ruler.Venus,
    "Menthae : all kinds of mint": Ruler.Venus,
    "Nepeta cataria: catnip": Ruler.Venus,
    "Orchis : all kinds of orchids": Ruler.Venus,
    "Oxalis acetosella : wood sorrel, clover sorrel": Ruler.Venus,
    "Persica vulgaris: peach": Ruler.Venus,
    "Phaseolus Pulgaris: dwarf bean, running bean (with the Moon)": Ruler.Venus,
    "Prunus cerasus : morello cherry, sour cherry": Ruler.Venus,
    "Pyrus malus: apple (with the Sun)": Ruler.Venus,
    "Rosa damascena : rose (with Jupiter)": Ruler.Venus,
    "Sambucus nigra : elder (with Saturn and Mercury)": Ruler.Venus,
    "Saponaria officinalis: soapwort, soap plant, soapweed": Ruler.Venus,
    "Senecio jacobaea: tansy ragwort": Ruler.Venus,
    "Senecio vulgaris : groundsel": Ruler.Venus,
    "Solidago virga aurea: goldenrod": Ruler.Venus,
    "Thymus serpyllum: wild thyme (with the Sun)": Ruler.Venus,
    "Thymus vulgaris : garden thyme (with the Sun)": Ruler.Venus,
    "Triticum sativum : wheat (with Jupiter)": Ruler.Venus,
    "Viola odorata : violet (with the Moon)": Ruler.Venus,
}

export default Plants;